package com.gqlsurfmapper.gqlasa;

import burp.api.montoya.MontoyaApi;

import javax.swing.*;
import java.awt.*;

public class PathQueryBuilderPanel extends JPanel
{
    public PathQueryBuilderPanel(MontoyaApi api)
    {
        super(new BorderLayout());

        JTextArea info = new JTextArea(
            "Phase 2 plan:\n" +
            "- Load schema (from Schema tab)\n" +
            "- Choose target type (dropdown + manual)\n" +
            "- Show paths table (index, path, depth, root field, required args)\n" +
            "- Search/filter + pagination (25)\n" +
            "- On row click: show pretty query + Copy Body\n" +
            "- Send to Repeater (caption generated by extension)\n"
        );
        info.setEditable(false);
        info.setLineWrap(true);
        info.setWrapStyleWord(true);

        add(new JScrollPane(info), BorderLayout.CENTER);
    }
}
